---
abstract: 'Easy (and fast) CSV parsing and building'
author:
  - 'Tom Peters <weters@me.com>'
build_requires:
  Test::Deep: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-CSV-Easy_XS
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.01
version: 0.50
